config/routes.rb
Rails.application.routes.draw do

  get 'procedures/create'

  get 'procedures/edit'

  get 'procedures/destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, except: [:index] do
    resources :proposals do
      resources :comments do
      end
        resources :experiments, except: [:index] do
          resources :procedures, except: [:index] do
            resources :observations, only: [:new, :create] do
              resources :comments, only: [:new, :create]  do
              end
            end
          end
          resources :observations, only: [:new, :create]  do
            resources :comments, only: [:new, :create]  do
            end
          end
          resources :comments, only: [:new, :create] do
          end
        end
    end
  end

  root 'proposals#index'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :proposals, {:foreign_key => :proposer_id}
  has_many :experiments, {:foreign_key => :experimenter_id}
  has_many :comments, {:foreign_key => :commenter_id}
  has_many :observations, {:foreign_key => :observer_id}

  has_secure_password

  validates :first_name, :last_name, :password_digest, :email, presence: true
  validates :email, uniqueness: true
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    if !logged_in?
      redirect_to '/login'
    elsif @user != current_user
      render '404'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to "/",:notice => "signed up"
    else
      @errors = @user.errors.full_messages
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :access)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
  <% if @errors %>
    <%= @errors %>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Register</h1>
    <%= form_for :user, url: '/users', :html => {:class => "form-group"} do |f| %>
    <div class="form-group">
      <label for="first_name">First Name: </label>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label for="last_name">Last Name: </label>
      <%= f.text_field :last_name, class: 'form-control' %>
    <div/>

    <div class="form-group">
      <label for="email" class="col-sm-2 control-label">Email: </label>
       <%= f.text_field :email, class: 'form-control' %>
    <div/>

    <div class="form-group">
      <label for="Password">Password: </label>
      <%= f.password_field :password, class: 'form-control' %>
    <div/>

    <div class="form-group">
      <label for="password_conf">Password Confirmation: </label>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    <div/><br>
      <%= f.submit "Submit", class: "btn btn-default" %><br>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<h1> Welcome <%= @user.full_name %> </h1>
<p>Lab position: <%= @user.access %></p>


<%  if @user.access == "faculty" %>
<div>
  <h3> Proposals : </h3>
    <ul>
      <% @user.proposals.each do |prop| %>
        <li><h3><%= link_to prop.summary, user_proposal_path(@user,prop) %></h3></li><br>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"><%= link_to 'Edit', edit_user_proposal_path(@user,prop) %></span>
        <span class="glyphicon glyphicon-fire" aria-hidden="true"><%= link_to 'Delete', user_proposal_path(@user,prop), method: :delete, data: { confirm: 'Are You Sure?'} %> </span>
      <% end %>
      <ul>
</div>

 <span class="glyphicon glyphicon-wrench" aria-hidden="true"><%= link_to 'Create a new proposal', new_user_proposal_path(@user) %> </span>

<% else %>
  <h3> Experiments : <h3>
    <ul>
      <% @user.experiments.each do |ex| %>
      <li><span class="glyphicon glyphicon-leaf" aria-hidden="true"><%= link_to ex.title, user_proposal_experiment_path(ex.experimenter, ex.proposal, ex) %></li><br>
    </ul>
      <% end %>
<% end %>