config/routes.rb
Rails.application.routes.draw do

  get 'procedures/create'

  get 'procedures/edit'

  get 'procedures/destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, except: [:index] do
    resources :proposals do
      resources :comments do
      end
        resources :experiments, except: [:index] do
          resources :procedures, except: [:index] do
            resources :observations, only: [:new, :create] do
              resources :comments, only: [:new, :create]  do
              end
            end
          end
          resources :observations, only: [:new, :create]  do
            resources :comments, only: [:new, :create]  do
            end
          end
          resources :comments, only: [:new, :create] do
          end
        end
    end
  end

  root 'proposals#index'

end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :experimenter, {:class_name => "User"}
  belongs_to :proposal
  has_many :procedures
  has_many :comments , as: :commentable
  has_many :observations, as: :observable

  validates :title, presence: true
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  include SessionsHelper
  def new
    @experiment = Experiment.new
    @proposal = Proposal.find(params[:proposal_id])
    @user = User.find(params[:user_id])
  end

  def create
    @user = current_user
    @proposal = Proposal.find(params[:proposal_id])
    @experiment = @user.experiments.new(experiment_params)

    # @proposal.experiments()
    if @experiment.save
      redirect_to user_proposal_path(@proposal.proposer, @proposal)
    else
      render '/experiments/new'
    end
  end

  def show
    @experiment = Experiment.find_by(id: params[:id])
  end

  def edit
    @experiment = Experiment.find_by(id: params[:id])
    @proposal = @experiment.proposal
    @user = User.find(params[:user_id])
    if current_user != @experiment.experimenter
      redirect_to @experiment
    end
  end

  def update
    @user = current_user
    @proposal = Proposal.find(params[:proposal_id])
    @experiment = Experiment.find_by(id: params[:id])
    if current_user == @experiment.experimenter
      if @experiment.update(experiment_update_params)
        redirect_to user_proposal_path(@experiment.proposal.proposer, @experiment.proposal)
      else
        @errors = @experiment.errors.full_messages
        render '/experiments/edit'
      end
    else
      redirect_to @experiment
    end
  end

  def destroy
    @proposal = Proposal.find(params[:proposal_id])
    @experiment = Experiment.find_by(id: params[:id])
    if current_user == @experiment.experimenter
      @experiment.destroy
      redirect_to user_proposal_path(@experiment.proposal.proposer, @experiment.proposal)
    else
      redirect_to @experiment
    end
  end

  private
  def experiment_update_params
    params.require(:experiment).permit(:title, :proposal_id, :results, :conclusions)
  end
  def experiment_params
    params.require(:experiment).permit(:title, :proposal_id)
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_errors.html.erb
<% if @errors %>
    <div id="error_explanation">
      <ul>
      <% @errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/experiments/edit.html.erb
<% if @errors %>
  <%= render 'errors' %>
<% end %>
<%= form_for [@user, @proposal, @experiment] do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", id: "exampleTextarea", rows: "1"  %><br>
  </p>
  <p>
    <%= f.label :results %><br>
    <%= f.text_area :results, class: "form-control", id: "exampleTextarea", rows: "5"  %><br>
  </p>
  <p>
    <%= f.label :conclusions %><br>
    <%= f.text_area :conclusions, class: "form-control", id: "exampleTextarea", rows: "5" %><br>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.select :status, ['Open', 'In Progress', 'Closed', 'Archived'] %><br>

    <%= f.submit %>
  </p>
<% end %>

app/views/experiments/new.html.erb
<div class="form-group">
  <%= form_for [@user, @proposal, @experiment] do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %><br>
  </p>
  <%= f.hidden_field :proposal_id, :value => @proposal.id %>
  <p>
    <%= f.submit %>
  </p>
  <% end %>
</div>

app/views/experiments/show.html.erb
<h1> Experiment: <%= @experiment.title %> </h1>
<p> Experiment Conducted by : <%= @experiment.experimenter.full_name %> </p>

<div>
  <h4>Status:</h4><%= @experiment.status %>
</div>

<div>
  <h4> Results: </h4>
  <% if !@experiment.results %>
    <p> The experiment is still in progress </p>
  <% else %>
    <%= @experiment.results %>
  <% end %>
</div>

<div>
  <h4> Conclusions: </h4>
  <% if !@experiment.conclusions %>
    <p> The experiment is still in progress </p>
  <% else %>
    <%= @experiment.conclusions %>
  <% end %>
</div>


<div>
  <h4> Procedures: </h4>
  <span><%= link_to 'Add procedure' , new_user_proposal_experiment_procedure_path(@experiment.proposal.proposer, @experiment.proposal, @experiment) %></span>
  <% if @experiment.procedures.any? %>
    <% @experiment.procedures.each do |pro| %>
    <ul>
      <li><%= pro.steps %></li>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"><%= link_to "Edit", edit_user_proposal_experiment_procedure_path(@experiment.proposal.proposer,@experiment.proposal, @experiment) %>
      <span class="glyphicon glyphicon-fire" aria-hidden="true"></span><%= link_to "Delete", user_proposal_experiment_procedure_path(@experiment.proposal.proposer,@experiment.proposal, @experiment), method: :delete, data: { confirm: 'Are you sure?' } %>
    </ul>
    <% end %>
  <% end %>
</div>

<div>
    <% if @experiment.observations.any? %>
    <h4> Observations: </h4>
    <% @experiment.observations.each do |obs| %>
    <ul>
      <li><%= obs.body %> - <%= obs.observer.full_name %></li>
    </ul>
      <% end %>
    <% end %>
</div>


<% if @experiment.experimenter == current_user %>
<span class="glyphicon glyphicon-pencil" aria-hidden="true"><%= link_to "Edit", edit_user_proposal_experiment_path(@experiment.proposal.proposer,@experiment.proposal, @experiment) %>
<span class="glyphicon glyphicon-fire" aria-hidden="true"><%= link_to 'Destroy', user_proposal_experiment_path(@experiment.proposal.proposer, @experiment.proposal, @experiment), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to "Back", user_proposal_path(@experiment.proposal.proposer, @experiment.proposal) %>

<% end %>

<% if logged_in? %>
  <%= link_to "Add an Observation", new_user_proposal_experiment_observation_path(@experiment.proposal.proposer, @experiment.proposal, @experiment) %>
<% end %>