config/routes.rb
Rails.application.routes.draw do

  get 'procedures/create'

  get 'procedures/edit'

  get 'procedures/destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, except: [:index] do
    resources :proposals do
      resources :comments do
      end
        resources :experiments, except: [:index] do
          resources :procedures, except: [:index] do
            resources :observations, only: [:new, :create] do
              resources :comments, only: [:new, :create]  do
              end
            end
          end
          resources :observations, only: [:new, :create]  do
            resources :comments, only: [:new, :create]  do
            end
          end
          resources :comments, only: [:new, :create] do
          end
        end
    end
  end

  root 'proposals#index'

end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :proposer, {:class_name => "User"}
  has_many :comments , as: :commentable
  has_many :experiments

  validates :summary, :hypothesis, :status, presence: true
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
   def index
    @proposals = Proposal.all
   end

  def show
    @user = User.find(params[:user_id])
    @proposal = Proposal.find_by(id: params[:id])

    render '404' if @proposal == nil

  end

  def create
    @user = current_user
    @proposal = @user.proposals.new(proposal_params)

    if @proposal.save
      redirect_to @user
    else
      @errors = @proposal.errors.full_messages
      render 'new'
    end
  end

  def new
    @user = current_user
    @proposal = Proposal.new
  end

  def edit
    if logged_in?
      @user = User.find(params[:user_id])
      @proposal = Proposal.find(params[:id])
      if @user != current_user
        @errors = ["Wrong credentials"]
        render '/sessions/new'
      end
    else
      redirect_to '/login'
    end
  end

  def update
    @proposal = Proposal.find(params[:id])
    if @proposal.update(proposal_params)
      redirect_to user_proposal_url
    else
      render 'edit'
    end
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    redirect_to @proposal.proposer
  end

  private
  def proposal_params
    params.require(:proposal).permit(:summary, :hypothesis, :status)
  end

end

app/helpers/proposals_helper.rb
module ProposalsHelper
  def no_proposal_found
    
  end
end
# def log_in(user)
#   session[:user_id] = user.id
# end
#
# # Returns the current logged-in user (if any).
# def current_user
#   @current_user ||= User.find_by(id: session[:user_id])
# end
#
# def logged_in?
#   !current_user.nil?
# end
#
# def log_out
#   session.delete(:user_id)
#   @current_user = nil
# end
#
# def not_logged_in
#   if !logged_in?
#     redirect '/login'
#   end
# end

app/views/proposals/404.html.erb
<div class="container">
    <div class="row">
    <div class="error-template">
	    <h1>Oops!</h1>
	    <h2>404 Not Found</h2>
	    <div class="error-details">
		Sorry, an error has occured, Requested page not found!<br>
	    </div>
	    <div class="error-actions">
		<a href="/" class="btn btn-primary">
		    <i class="icon-home icon-white"></i> Take Me Home </a>
	    </div>
	</div>
    </div>
</div>

app/views/proposals/_form.html.erb
<div class="form-group">

  <% if @proposal.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@proposal.errors.count, "error") %>
      prohibited this article from being saved:
    </h2>
    <ul>
      <% @proposal.errors.full_messages.each do |msg| %>
      <li><%= msg %> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= form_for [@user, @proposal], :html => {:class => "form-group"} do |f| %>
    <div class="form-group">
      <label for="summary">Summary: </label>
      <%= f.text_field :summary, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="hypothesis">Hypothesis </label>
      <%= f.text_field :hypothesis, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :status %>
      <%= f.select :status, ['Open', 'In Progress', 'Closed', 'Archived'] %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
  <% end %>

</div>

app/views/proposals/create.html.erb
<h1>Proposals#create</h1>
<p>Find me in app/views/proposals/create.html.erb</p>

app/views/proposals/destroy.html.erb
<h1>Proposals#destroy</h1>
<p>Find me in app/views/proposals/destroy.html.erb</p>

app/views/proposals/edit.html.erb
<h2>Update Your Proposal</h2>

<%= render 'form' %>

app/views/proposals/index.html.erb
<h3 class="title is-3"> Proposals </h3>

<% if @proposals %>
  <% @proposals.each do |proposal| %>

  <ul>
    <h4><li><span class="glyphicon glyphicon-search" aria-hidden="true"></span><%= link_to proposal.summary, user_proposal_path(proposal.proposer, proposal) %></li><br>Status- <%= proposal.status %></h4><br>
  </ul>
  <% end %>
<% else %>
  <h3> There are currently no proposals available! <h3>
<% end %>

app/views/proposals/new.html.erb
<h2>Create a New Proposal</h2>

<%= render 'form' %>

app/views/proposals/show.html.erb
<h2>Proposal #<%= @proposal.id %></h2>
<div id="proposal-container">
  <h3>Proposed By:</h3>
  <h5><%= @user.first_name %> <%= @user.last_name %></h5>
  <h3>Summary:</h3>
  <h5><%= @proposal.summary %></h5>
  <h3>Hypothesis:</h3>
  <h5><%= @proposal.hypothesis %></h5>
  <h3>Status:</h3>
  <h5><%= @proposal.status %></h5>


<% if logged_in? && current_user == @proposal.proposer %>
</div>
<div id="proposal-links">
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><%= link_to 'Edit', edit_user_proposal_path(@user, @proposal) %>
  <span class="glyphicon glyphicon-fire" aria-hidden="true"></span><%= link_to 'Destroy', user_proposal_path(@user, @proposal), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>

<% if logged_in? && current_user.access == "labtech" %>
<div>
  <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span><%= link_to 'Create new experiment', new_user_proposal_experiment_path(@proposal.proposer, @proposal) %>
</div>
<% end %>

<div>
  <% if @proposal.experiments.any? %>
  <h5> Current Experiments: </h5>
  <ul>
    <% @proposal.experiments.each do |exp| %>
      <li><span class="glyphicon glyphicon-leaf" aria-hidden="true"><%= link_to exp.title , user_proposal_experiment_path(@proposal.proposer,@proposal, exp) %></li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/proposals/update.html.erb
<h1>Proposals#update</h1>
<p>Find me in app/views/proposals/update.html.erb</p>